data:
  batch_size: 32
  dataset_root: data/
  dataset_name: mvtec_ad
  category_name: bottle
  multi_category: false
  transform_type: default
  num_workers: 1
  prefetch_factor: 1
  pin_mem: true
logging:
  folder: logs/mim/train/
  write_tag: base_vgg19_ep2000_m75_bs32
  ckpt_interval: 3000
mask:
  mask_strategy: random
  mask_ratio: 0.75
  aspect_ratio:  # for block mask
  - 0.75
  - 1.5  
  mask_scale:  # for block mask
  - 0.1
  - 0.4
model:
  mim_model_type: mim_base
  backbone_name: vgg19
  backbone_indices:
  - 3
  - 8
  - 17
  - 26
  feature_res: 64
  in_resolution: 224
  use_bfloat16: false
  resume_path: null
  patch_size: 2
optimization:
  epochs: 2000
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  warmup_lr: 0.001
  start_lr: 0.0002
  warmup_epochs: 40
  start_weight_decay: 0.04
  grad_clip_norm: 0.0

