data:
  batch_size: 1
  dataset_root: data/
  dataset_name: mvtec_ad
  category_name: bottle
  multi_category: false
  transform_type: default
  num_workers: 1
  prefetch_factor: 1
  pin_mem: true
logging:
  folder: logs/mim/eval/
  write_tag: debug
mask:
  mask_strategy: random
  mask_ratio: 0.5
  num_masks: 10
  aspect_ratio:  # for block mask
  - 0.75
  - 1.5  
  mask_scale:  # for block mask
  - 0.1
  - 0.4
model:
  mim_model_type: mim_base
  backbone_name: vgg19
  backbone_indices:
  - 3
  - 8
  - 17
  - 26
  feature_res: 64
  in_resolution: 224
  use_bfloat16: false
  resume_path: logs/mim/train/debug.pth
  patch_size: 2